version: '3'

# Docker Compose file for Node and Nginx setup

services:
    # Node.js Service
    node:
        image: node:latest
        working_dir: /app
        volumes:
            - .:/app
        ports:
            - "4040:4040"
        tty: true

    # Nginx Service
    nginx:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
