version: '3'

# Docker Compose file for PHP and Nginx setup

services:

  # PHP Service
  php:
    build: .docker/php
    ports:
      - "9000:9000"
    environment:
      PHP_IDE_CONFIG: "serverName=ace3"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/var/www:cached
      # - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

  # Nginx Service
  nginx:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  # MySQL Service
  mysql:
    image: mariadb:10.6
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: api
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql